version: '3'
services:
  saml-idp:
     build:
        context: .
     ports:
        - "127.0.0.1:7000:7000"
     expose:
        - "7000"
     environment:
        - SP_HOST=${HOST}
        - SP_ENTITY_ID=${ENTITY_ID}
        - SP_ACS_POST_PATH=${ACS_POST_PATH}
        - SP_LS_POST_PATH=${LS_POST_PATH}
        - IDP_SIGN_RESPONSE=${SIGN_RESPONSE}
